[build]
  command = "npm ci && next build"
  publish = ".next"
  base = "."  # Ensures build from project root
  environment = { NODE_VERSION = "18" }  # Match your local Node version

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [build.environment]
  NODE_VERSION = "22.19.0"